#!/bin/bash

set -e

rm -fr build
mkdir -p build/src

# Copy static resources
cp -r public build

# Copy LICENSE, README and package.json
cp LICENSE package.json README.md build

# Copy bin script
cp -r bin build

# Copy server
cp -r src build
rm -fr build/src/client
rm -f build/src/dev-assets.ts

# Bundle and minify client JS
npx webpack --config webpack.prod.cjs
